### ISSUE TITLE
multiple match display broken

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/nodebb-plugin-arma3-slotting#28]
![multiple](https://cloud.githubusercontent.com/assets/500164/23831624/a7d2f9ee-0725-11e7-9d58-95df58246512.JPG)

**Comment by Fusselwurm** [comment]
@nomisum ich hab n paar dinge nach master gepusht. – schau mal rauf, ich glaub es fehlt nur noch stylefixes (margins)
