### ISSUE TITLE
visualize forum groups

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/nodebb-plugin-arma3-slotting#45]
it would be reaaally nice if we could see the forum groups everyone is a member of.

e.g. have a toggle to switch from displaying avatars to forum groups (symbolized by color/initial letter)

**Comment by nomisum** [comment]
i wanted to mark this with a fat outline, but toggling seems smarter/more focused

**Comment by Fusselwurm** [comment]
I *think* I'll just add `groups: ['Adler', 'Gastspieler', …]` to the user models

**Comment by Fusselwurm** [comment]
group names have been added to user models. group detail data can and probably should be fetched via `/api/groups`
