### ISSUE TITLE
Remove optionsHandle

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/nodebb-plugin-arma3-slotting#75]
We do not need to set the cors headers in the `optionsHandle` manually, because those headers are set by the forum itself.

https://github.com/gruppe-adler/nodebb-plugin-arma3-slotting/blob/e36dbb615d894fe58db2406762c271347f2d54e2/lib/api.ts#L248-L257

Also we do not need the `methodNotAllowed`, because it will catch any requests and close the connection, before the forum can set the cors http headers.

https://github.com/gruppe-adler/nodebb-plugin-arma3-slotting/blob/e36dbb615d894fe58db2406762c271347f2d54e2/lib/api.ts#L89-L95

**Comment by DerZade** [comment]
(This is already monkey patched in our production forum 😉)

**Comment by Fusselwurm** [comment]
#74
